# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eb82a817447663b80c1a7dc63f677c80680ea78a6f9771aa1f0de85ad3a8d90357d64cfe8f179c32ae5747b291ed73ad1f61428d30c13a53be446cfb91ac421

test:
  secret_key_base: 3937cd05b0f18c08b6e52ac3b668b98ef6b45ec9620f71fb18156ee04c3f1e1923480c33962aa03b155e89e07bf77b9218e6d216fc3f324fa8b2e80351209b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
